"use client";

import { Geist, Geist_Mono } from "next/font/google";
// import "antd/dist/reset.css"; // Import Ant Design styles
import "./globals.css";
import { ToastContainer } from "react-toastify";
import useAuthStore from "../store/authStore"; // Import Zustand store
import Header from "@/component/Header";
import useNotificationStore from "@/store/notificationStore";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { user, logout, isHydrated } = useAuthStore();

  const { startListening, stopListening, fetchNotifications } =
    useNotificationStore();

  useEffect(() => {
    if (user) {
      fetchNotifications(); // Initial fetch
      startListening(); // Start SSE connection
    } else {
      stopListening(); // Stop SSE if user logs out
    }
  }, [user]); // Run when user logs in or out

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isHydrated && (
          <>
            <Header />
            {children}
            <ToastContainer />
          </>
        )}
      </body>
    </html>
  );
}
